# FINANCIAL ASSUMPTIONS

# CAPITAL COST FACTORS
[direct_cost_factors]
equipment_installation = 0.40           # 25-55% of total equipment cost
instrumentation_and_controls = 0.20     # 8-50% of total equipment cost
piping = 0.30                           # 10-80% of total equipment cost
electrical_installations = 0.25         # 10-40% of total equipment cost
buildings = 0.35                        # 10-70% of total equipment cost
yard_improvements = 0.20                # 40-100% for yard + service faiclities of total equipment cost
service_facilities = 0.40               # 40-100% for yard + service faiclities of total equipment cost
land = 0.06                             # 4-8% of total equipment cost

[indirect_cost_factors]
engineering_and_supervision = 0.15      # 5-30% of direct costs
legal_expenses = 0.02                   # 1-3% of FCI
contractors_fee = 0.15                  # 10-20% of FCI
contingency = 0.10                      # 5-15% of FCI

[working_capital]
working_capital = 0.15                  # 10-20% of TCI

# PERCENT SHARE FOR FIXED O&M COSTS
[direct_operating_cost_factors]
local_taxes = 0.01                          # 1% of fixed capital investment
insurance = 0.005                           # 0.5% of fixed capital investment
maintenance_and_repairs = 0.055             # 5.5% of fixed capital investment
operating_supplies = 0.0015                 # 0.15% of fixed capital investment
plant_overhead = 0.6                        # 50-70% of operating labor, supervision, and maintenance
admin_costs = 0.2                           # 20% of operating labor, supervision, and maintenance
research_and_development = 0.025            # 2.5% of total product cost

[financial_assumptions]
equity = 0.2 # Equity [Weibel 2018]
loan_interest = 0.055 # Loan interest [Weibel 2018]
loan_term = 10 # Loan term years [Weibel 2018]
WC = 0.05 # Working capital
FCIDet = 1 # what is this?????????????????????
CostNGGrowth = 0.0473 # 
CostNGSTD = 1 # Variable is not implemented
CPY = 3 # Construction period year
CY_1 = 0.08 # Proportion of FCI spent during construction year 1
CY_2 = 0.6 # Proportion of FCI spent during construction year 2
CY_3 = 0.32 # Proportion of FCI spent during construction year 3
DPY = 10 # Depreciation period year
inflation = 0.02
HPY = 8400 # Operating hours per year
VPY = 20 # Valuation period years [Brynolf 2017]
OPD = 350 # operating days
prod_capacity1 = 0.75 # Production capacity in year 1 (50% in first 6 months, 100% onward) [Pearlson 2013]
prod_capacity2 = 1 # Production capacity in year 2 (100%)
WACC = 0.06 # Discount rate [IEA Future of Hydrogen 2020]
ITR = 0.173 # Income tax rate Tyner and Brandt - FAA Ascent**
cost_labor = 15 # $/hr
